### ISSUE TITLE
Meta issue for workshop

### ISSUE THREAD

**Issue by gvegayon** [EpiForeSITE/r-pkgs-workshop#1]
This issue only sees things that are relevant content-wide. Logistics are managed internally by ForeSITE.

- [x] First version of the program (website).
- [x] Information about the venue, including instructions (website).
- [ ] Setup posit.cloud environment and instructions.
- [ ] Design a checklist or a template repo for R packages.
- [ ] Set up a profiles page featuring attendees.
